version: "3.7"
services:
  front:
    image: zhlcy2022/front
    build: ./front
    depends_on:
      - dbServer
    volumes:
      - ./front:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"
  dbServer:
    image: zhlcy2022/db_server
    build: ./backend/dbServer
    depends_on:
      - mongo
    volumes:
      - ./backend/dbServer:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017/
      PORT: 8000
  fileServer:
    image: zhlcy2022/file_server
    build: ./backend/fileServer
    depends_on:
      - mongo
    volumes:
      - ./backend/fileServer:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8001:8001"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017/
      PORT: 8001
  mongo:
    image: mongo
    command: --wiredTigerCacheSizeGB 1
    restart: always
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  database:
